export default {
  root: {
    backgroundColor: "white",
    border: "2px solid black",
    borderRadius: "5px",
    padding: "0.5rem",
    position: "relative",
    Overflow: "hidden",
    cursor: "pointer",
    "&:hover svg": {
      opacity: 1,
    },
  },
  colors: {
    backgroundColor: "#daele3",
    height: "150px",
    width: "100%",
    borderRadius: "5px",
    Overflow: "hidden",
    marginBottom: "-2px",
  },
  title: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    margin: "0",
    color: "black",
    paddingTop: "0.5rem",
    fontSize: "1rem",
    position: "relative",
  },
  emoji: { marginLeft: "0.5rem", fontSize: "1.5rem" },
  miniColor: {
    height: "25%",
    width: "20%",
    display: "inline-block",
    margin: "0 auto",
    position: "relative",
    marginBottom: "-3.5px",
  },

  delete: {},
  deletIcon: {
    color: "white",
    backgroundColor: "#eb3d30",
    width: "40px",
    height: "40px",
    position: "absolute",
    right: 0,
    top: 0,
    padding: "2px",
    zIndex: 10,
    opacity: 0,
  },
};
